version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "maxxidata"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
volumes:
    db-data:
networks: 
  postgres-compose-network:
    driver: bridge