export const jwtConstants = {
    secret: 'eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTYzOTMxMDY2OCwiaWF0IjoxNjM5MzEwNjY4fQ.eqDwsDLSLfsZ1plv0MQ3USywHwGzRBBnjQ-hHr-KGXg',
};